"""
Configuration constants for easy-wallpaper.

Defines categories, moods, resolutions, and provider mapping.
"""

from providers import (
    PexelsProvider,
    PixabayProvider,
    WaifuImProvider,
    CatgirlProvider,
    UnsplashProvider,
    WallhavenProvider,
    BingProvider,
    PicsumProvider,
    NasaApodProvider,
    TheCatApiProvider,
    TheDogApiProvider,
    MetMuseumProvider,
    WikimediaCommonsProvider,
    LoremFlickrProvider,
    RedditProvider,
    DeviantArtProvider,
    KonachanProvider,
    FoodishProvider,
    FoxProvider,
    MemeProvider,
    ZenQuotesProvider,
    SafebooruProvider,
    XKCDProvider,
    DogCeoProvider,
    ImgFlipProvider,
    CoffeeProvider,
    CataasProvider,
    PlaceBearProvider,
    PlaceDogProvider,
    RobohashProvider,
    InspirobotProvider,
    JikanProvider,
    ScryfallProvider,
    HTTPCatsProvider,
    ArtInstituteProvider,
    RickAndMortyProvider,
    OpenLibraryProvider,
    TheMealDbProvider,
    TheCocktailDbProvider,
    GeneratedPeopleProvider,
    TheSportsDbProvider,
    ClevelandMuseumProvider,
    DisneyProvider,
    WaifuPicsProvider,
    HarryPotterProvider,
    KitsuProvider,
    SpaceXProvider,
    DummyJsonProvider,
    RandomMetaProvider,
    PokeApiProvider,
    GhibliProvider,
    DigimonProvider,
    ZeldaCompendiumProvider,
    MinecraftSkinProvider,
    YugiohProvider,
    iTunesArtworkProvider,
    CountryFlagsProvider,
    AmiiboApiProvider,
    CoinCapProvider,
    DiceBearProvider,
)

# Provider mapping
PROVIDERS = {
    "1": PexelsProvider(),
    "2": PixabayProvider(),
    "3": WaifuImProvider(),
    "4": CatgirlProvider(),
    "5": UnsplashProvider(),
    "6": WallhavenProvider(),
    "7": BingProvider(),
    "8": PicsumProvider(),
    "9": NasaApodProvider(),
    "10": TheCatApiProvider(),
    "11": TheDogApiProvider(),
    "12": MetMuseumProvider(),
    "13": WikimediaCommonsProvider(),
    "14": LoremFlickrProvider(),
    "15": RedditProvider(),
    "16": DeviantArtProvider(),
    "17": KonachanProvider(),
    "18": FoodishProvider(),
    "19": FoxProvider(),
    "20": MemeProvider(),
    "21": ZenQuotesProvider(),
    "22": SafebooruProvider(),
    "23": XKCDProvider(),
    "24": DogCeoProvider(),
    "25": ImgFlipProvider(),
    "26": CoffeeProvider(),
    "27": CataasProvider(),
    "28": PlaceBearProvider(),
    "29": PlaceDogProvider(),
    "30": RobohashProvider(),
    "31": InspirobotProvider(),
    "32": JikanProvider(),
    "33": ScryfallProvider(),
    "34": HTTPCatsProvider(),
    "35": ArtInstituteProvider(),
    "36": RickAndMortyProvider(),
    "37": OpenLibraryProvider(),
    "38": TheMealDbProvider(),
    "39": TheCocktailDbProvider(),
    "40": GeneratedPeopleProvider(),
    "41": TheSportsDbProvider(),
    "42": ClevelandMuseumProvider(),
    "43": DisneyProvider(),
    "44": WaifuPicsProvider(),
    "45": HarryPotterProvider(),
    "46": KitsuProvider(),
    "47": SpaceXProvider(),
    "48": DummyJsonProvider(),
    "49": PokeApiProvider(),
    "50": GhibliProvider(),
    "51": DigimonProvider(),
    "52": ZeldaCompendiumProvider(),
    "53": MinecraftSkinProvider(),
    "54": YugiohProvider(),
    "55": iTunesArtworkProvider(),
    "56": CountryFlagsProvider(),
    "57": AmiiboApiProvider(),
    "58": CoinCapProvider(),
    "59": DiceBearProvider(),
}

# Categories for each provider
CATEGORIES = {
    "Pexels": [
        "nature",
        "landscape",
        "urban",
        "beach",
        "mountain",
        "forest",
        "city",
        "sky",
    ],
    "Pixabay": [
        "abstract",
        "animals",
        "art",
        "backgrounds",
        "buildings",
        "business",
        "computer",
        "food",
        "nature",
        "people",
        "places",
        "science",
        "technology",
    ],
    "waifu.im": [
        "waifu",
        "maid",
        "miko",
        "oppai",
        "uniform",
        "kitsune",
        "demon",
        "elf",
    ],
    "nekos.moe": [
        "safe sfw",
        "nsfw",
        "mixed",
    ],
    "Unsplash": [
        "nature",
        "wallpapers",
        "travel",
        "people",
        "street-photography",
        "animals",
        "architecture",
    ],
    "Wallhaven": [
        "anime",
        "general",
        "people",
        "fantasy",
        "cyberpunk",
        "nature",
        "scifi",
    ],
    "Bing": [
        "Random",
        "Today",
        "Yesterday",
        "2 days ago",
        "3 days ago",
        "4 days ago",
        "5 days ago",
        "6 days ago",
        "7 days ago",
    ],
    "Picsum": [
        "random",
        "seed",
    ],
    "NASA APOD": [
        "Today",
        "Random",
    ],
    "TheCatAPI": [
        "Random",
    ],
    "TheDogAPI": [
        "Random",
    ],
    "The Met": [
        "sunflowers",
        "landscape",
        "portrait",
        "arms and armor",
        "egyptian",
        "asian art",
        "islamic art",
        "modern art",
    ],
    "Wikimedia Commons": [
        "nature",
        "landscape",
        "space",
        "architecture",
        "animals",
        "city",
        "historical",
        "painting",
    ],
    "Lorem Flickr": [
        "kitten",
        "puppy",
        "paris",
        "brazil",
        "nature",
        "city",
        "food",
        "car",
    ],
    "Reddit": [
        "wallpapers",
        "EarthPorn",
        "CityPorn",
        "SpacePorn",
        "AnimalPorn",
        "FoodPorn",
        "Art",
    ],
    "DeviantArt": [
        "digital art",
        "fantasy",
        "anime",
        "landscape",
        "sci-fi",
        "horror",
    ],
    "Konachan": [
        "original",
        "landscape",
        "city",
        "school_uniform",
        "long_hair",
        "clouds",
        "sky",
    ],
    "Foodish": [
        "Random",
        "Pizza",
        "Burger",
        "Pasta",
        "Biryani",
        "Rice",
        "Dessert",
    ],
    "Random Fox": [
        "Random",
    ],
    "Meme API": [
        "wholesomememes",
        "dankmemes",
        "me_irl",
        "ProgrammerHumor",
        "memes",
        "catmemes",
        "dogmemes",
    ],
    "ZenQuotes": [
        "Inspirational",
        "Random",
    ],
    "Safebooru": [
        "anime",
        "scenery",
        "general",
        "uniform",
        "original",
        "fantasy",
    ],
    "XKCD": [
        "Current",
        "Random",
    ],
    "Dog CEO": [
        "Random",
    ],
    "ImgFlip": [
        "Random",
    ],
    "Coffee": [
        "Random",
    ],
    "Cataas": [
        "Random",
        "cute",
        "funny",
        "orange",
        "black",
    ],
    "PlaceBear": [
        "Random",
    ],
    "PlaceDog": [
        "Random",
    ],
    "Robohash": [
        "Random",
        "Custom Text",
    ],
    "Inspirobot": [
        "Random",
    ],
    "Jikan (Anime)": [
        "Random",
        "Naruto",
        "One Piece",
        "Bleach",
        "Gintama",
    ],
    "Scryfall": [
        "Random",
        "Dragon",
        "Angel",
        "Goblin",
        "Elf",
        "Planeswalker",
    ],
    "HTTP Cats": [
        "Random",
        "404",
        "500",
        "200",
        "418",
    ],
    "Art Institute Chicago": [
        "Random",
        "Impressionism",
        "Modern Art",
        "Renaissance",
        "Landscape",
        "Portrait",
        "Japanese Prints",
        "Sculpture",
    ],
    "Rick and Morty": [
        "Random",
        "Rick Sanchez",
        "Morty Smith",
        "Summer Smith",
        "Beth Smith",
        "Jerry Smith",
        "Pickle Rick",
    ],
    "Open Library": [
        "Random",
        "Tolkien",
        "Harry Potter",
        "Asimov",
        "Science Fiction",
        "Fantasy",
        "Horror",
        "History",
    ],
    "TheMealDB": [
        "Random",
        "Chicken",
        "Beef",
        "Seafood",
        "Vegetarian",
        "Pasta",
        "Dessert",
    ],
    "TheCocktailDB": [
        "Random",
        "Margarita",
        "Mojito",
        "Martini",
        "Vodka",
        "Rum",
        "Gin",
    ],
    "ThisPersonDoesNotExist": [
        "Random",
    ],
    "TheSportsDB": [
        "Random",
        "Lionel Messi",
        "Cristiano Ronaldo",
        "LeBron James",
        "Stephen Curry",
        "Tom Brady",
        "Tiger Woods",
        "Roger Federer",
        "Serena Williams",
    ],
    "Cleveland Museum of Art": [
        "Random",
        "Painting",
        "Sculpture",
        "Drawing",
        "Print",
        "Photograph",
    ],
    "Disney": [
        "Random",
        "Mickey Mouse",
        "Donald Duck",
        "Goofy",
        "Elsa",
        "Simba",
        "Stitch",
    ],
    "Waifu.pics": [
        "waifu",
        "neko",
        "shinobu",
        "megumin",
        "bully",
        "cuddle",
        "cry",
        "hug",
        "awoo",
        "kiss",
        "lick",
        "pat",
        "smug",
    ],
    "Harry Potter": [
        "Random",
        "Harry Potter",
        "Hermione Granger",
        "Ron Weasley",
        "Draco Malfoy",
        "Gryffindor",
        "Slytherin",
    ],
    "Kitsu": [
        "Random",
        "Naruto",
        "One Piece",
        "Attack on Titan",
        "Demon Slayer",
        "Bleach",
    ],
    "SpaceX": [
        "Latest",
        "Random",
    ],
    "DummyJSON": [
        "Random",
        "Custom Text",
    ],
    "PokeAPI": [
        "Random",
        "Pikachu",
        "Charizard",
        "Mewtwo",
        "Eevee",
        "Gengar",
        "Lucario",
        "Rayquaza",
    ],
    "Studio Ghibli": [
        "Random",
        "Spirited Away",
        "My Neighbor Totoro",
        "Princess Mononoke",
        "Howl's Moving Castle",
        "Kiki's Delivery Service",
        "Ponyo",
    ],
    "Digimon": [
        "Random",
        "Agumon",
        "Gabumon",
        "Patamon",
        "Gatomon",
        "Greymon",
        "Angemon",
    ],
    "Zelda (BOTW)": [
        "Random",
        "Master Sword",
        "Hylian Shield",
        "Bokoblin",
        "Moblin",
        "Lizalfos",
        "Lynel",
        "Guardian Stalker",
    ],
    "Minecraft Skins": [
        "Random",
        "Notch",
        "Dream",
        "Technoblade",
        "Jeb_",
        "Steve",
        "Alex",
    ],
    "Yu-Gi-Oh!": [
        "Random",
        "Dark Magician",
        "Blue-Eyes White Dragon",
        "Exodia",
        "Kuriboh",
        "Slifer the Sky Dragon",
    ],
    "iTunes Artwork": [
        "Random",
        "Taylor Swift",
        "The Beatles",
        "Pink Floyd",
        "Star Wars",
        "Harry Potter",
        "Inception",
    ],
    "Country Flags": [
        "Random",
        "US",
        "GB",
        "JP",
        "DE",
        "FR",
        "CA",
        "AU",
        "BR",
    ],
    "Amiibo API": [
        "Random",
        "Mario",
        "Zelda",
        "Link",
        "Pikachu",
        "Kirby",
        "Samus",
        "Donkey Kong",
    ],
    "CoinCap (Crypto)": [
        "Random",
        "BTC",
        "ETH",
        "DOGE",
        "XRP",
        "SOL",
        "ADA",
    ],
    "DiceBear Avatars": [
        "Random",
        "adventurer",
        "avataaars",
        "bottts",
        "lorelei",
        "pixel-art",
    ],
    "🎲 Random Source": [
        "Random",
    ],
}

# Moods for filtering
MOODS = {
    "Pexels": ["calm", "vibrant", "dark", "bright"],
    "Pixabay": ["colorful", "minimal", "artistic", "realistic"],
    "waifu.im": [""],
    "nekos.moe": [""],
    "Unsplash": ["dark", "light", "colorful", "black_and_white"],
    "Wallhaven": [""],
    "Bing": [""],
    "Picsum": [""],
    "NASA APOD": [""],
    "TheCatAPI": [""],
    "TheDogAPI": [""],
    "The Met": [""],
    "Wikimedia Commons": [""],
    "Lorem Flickr": [""],
    "Reddit": ["hot", "top", "new", "rising"],
    "DeviantArt": [""],
    "Konachan": [""],
    "Foodish": [""],
    "Random Fox": [""],
    "Meme API": [""],
    "ZenQuotes": [""],
    "Safebooru": [""],
    "XKCD": [""],
    "Dog CEO": [""],
    "ImgFlip": [""],
    "Coffee": [""],
    "Cataas": [""],
    "PlaceBear": [""],
    "PlaceDog": [""],
    "Robohash": ["robots", "monsters", "cats"],
    "Inspirobot": [""],
    "Jikan (Anime)": [""],
    "Scryfall": [""],
    "HTTP Cats": [""],
    "Art Institute Chicago": [""],
    "Rick and Morty": [""],
    "Open Library": [""],
    "TheMealDB": [""],
    "TheCocktailDB": [""],
    "ThisPersonDoesNotExist": [""],
    "TheSportsDB": [""],
    "Cleveland Museum of Art": [""],
    "Disney": [""],
    "Waifu.pics": [""],
    "Harry Potter": [""],
    "Kitsu": [""],
    "SpaceX": [""],
    "DummyJSON": [""],
    "PokeAPI": [""],
    "Studio Ghibli": [""],
    "Digimon": [""],
    "Zelda (BOTW)": [""],
    "Minecraft Skins": [""],
    "Yu-Gi-Oh!": [""],
    "iTunes Artwork": [""],
    "Country Flags": [""],
    "Amiibo API": [""],
    "CoinCap (Crypto)": [""],
    "DiceBear Avatars": [""],
    "🎲 Random Source": [""],
}

# Initialize RandomMetaProvider with dependencies
PROVIDERS["0"] = RandomMetaProvider(PROVIDERS, CATEGORIES, MOODS)

# Resolution options
RESOLUTIONS = [
    "1920x1080",
    "1366x768",
    "1280x720",
    "2560x1440",
    "3840x2160",
]

# Default values
DEFAULT_PROVIDER = "3"  # waifu.im
DEFAULT_CATEGORY = "waifu"
DEFAULT_RESOLUTION = "1920x1080"
