"""
Configuration constants for easy-wallpaper.

Defines categories, moods, resolutions, and provider mapping.
"""

from providers import (
    PexelsProvider,
    PixabayProvider,
    WaifuImProvider,
    CatgirlProvider,
    UnsplashProvider,
    WallhavenProvider,
    BingProvider,
    PicsumProvider,
    NasaApodProvider,
    TheCatApiProvider,
    TheDogApiProvider,
    MetMuseumProvider,
    WikimediaCommonsProvider,
    LoremFlickrProvider,
    RedditProvider,
    DeviantArtProvider,
    KonachanProvider,
    FoodishProvider,
    FoxProvider,
    MemeProvider,
    ZenQuotesProvider,
    SafebooruProvider,
)

# Provider mapping
PROVIDERS = {
    "1": PexelsProvider(),
    "2": PixabayProvider(),
    "3": WaifuImProvider(),
    "4": CatgirlProvider(),
    "5": UnsplashProvider(),
    "6": WallhavenProvider(),
    "7": BingProvider(),
    "8": PicsumProvider(),
    "9": NasaApodProvider(),
    "10": TheCatApiProvider(),
    "11": TheDogApiProvider(),
    "12": MetMuseumProvider(),
    "13": WikimediaCommonsProvider(),
    "14": LoremFlickrProvider(),
    "15": RedditProvider(),
    "16": DeviantArtProvider(),
    "17": KonachanProvider(),
    "18": FoodishProvider(),
    "19": FoxProvider(),
    "20": MemeProvider(),
    "21": ZenQuotesProvider(),
    "22": SafebooruProvider(),
}

# Categories for each provider
CATEGORIES = {
    "Pexels": [
        "nature",
        "landscape",
        "urban",
        "beach",
        "mountain",
        "forest",
        "city",
        "sky",
    ],
    "Pixabay": [
        "abstract",
        "animals",
        "art",
        "backgrounds",
        "buildings",
        "business",
        "computer",
        "food",
        "nature",
        "people",
        "places",
        "science",
        "technology",
    ],
    "waifu.im": [
        "waifu",
        "maid",
        "miko",
        "oppai",
        "uniform",
        "kitsune",
        "demon",
        "elf",
    ],
    "nekos.moe": [
        "safe sfw",
        "nsfw",
        "mixed",
    ],
    "Unsplash": [
        "nature",
        "wallpapers",
        "travel",
        "people",
        "street-photography",
        "animals",
        "architecture",
    ],
    "Wallhaven": [
        "anime",
        "general",
        "people",
        "fantasy",
        "cyberpunk",
        "nature",
        "scifi",
    ],
    "Bing": [
        "Today",
        "Yesterday",
        "2 days ago",
        "3 days ago",
        "4 days ago",
        "5 days ago",
        "6 days ago",
        "7 days ago",
    ],
    "Picsum": [
        "random",
        "seed",
    ],
    "NASA APOD": [
        "Today",
        "Random",
    ],
    "TheCatAPI": [
        "Random",
    ],
    "TheDogAPI": [
        "Random",
    ],
    "The Met": [
        "sunflowers",
        "landscape",
        "portrait",
        "arms and armor",
        "egyptian",
        "asian art",
        "islamic art",
        "modern art",
    ],
    "Wikimedia Commons": [
        "nature",
        "landscape",
        "space",
        "architecture",
        "animals",
        "city",
        "historical",
        "painting",
    ],
    "Lorem Flickr": [
        "kitten",
        "puppy",
        "paris",
        "brazil",
        "nature",
        "city",
        "food",
        "car",
    ],
    "Reddit": [
        "wallpapers",
        "EarthPorn",
        "CityPorn",
        "SpacePorn",
        "AnimalPorn",
        "FoodPorn",
        "Art",
    ],
    "DeviantArt": [
        "digital art",
        "fantasy",
        "anime",
        "landscape",
        "sci-fi",
        "horror",
    ],
    "Konachan": [
        "original",
        "landscape",
        "city",
        "school_uniform",
        "long_hair",
        "clouds",
        "sky",
    ],
    "Foodish": [
        "Random",
        "Pizza",
        "Burger",
        "Pasta",
        "Biryani",
        "Rice",
        "Dessert",
    ],
    "Random Fox": [
        "Random",
    ],
    "Meme API": [
        "wholesomememes",
        "dankmemes",
        "me_irl",
        "ProgrammerHumor",
        "memes",
        "catmemes",
        "dogmemes",
    ],
    "ZenQuotes": [
        "Inspirational",
        "Random",
    ],
    "Safebooru": [
        "anime",
        "scenery",
        "general",
        "uniform",
        "original",
        "fantasy",
    ],
}

# Moods for filtering
MOODS = {
    "Pexels": ["calm", "vibrant", "dark", "bright"],
    "Pixabay": ["colorful", "minimal", "artistic", "realistic"],
    "waifu.im": [""],
    "nekos.moe": [""],
    "Unsplash": ["dark", "light", "colorful", "black_and_white"],
    "Wallhaven": [""],
    "Bing": [""],
    "Picsum": [""],
    "NASA APOD": [""],
    "TheCatAPI": [""],
    "TheDogAPI": [""],
    "The Met": [""],
    "Wikimedia Commons": [""],
    "Lorem Flickr": [""],
    "Reddit": ["hot", "top", "new", "rising"],
    "DeviantArt": [""],
    "Konachan": [""],
    "Foodish": [""],
    "Random Fox": [""],
    "Meme API": [""],
    "ZenQuotes": [""],
    "Safebooru": [""],
}

# Resolution options
RESOLUTIONS = [
    "1920x1080",
    "1366x768",
    "1280x720",
    "2560x1440",
    "3840x2160",
]

# Default values
DEFAULT_PROVIDER = "3"  # waifu.im
DEFAULT_CATEGORY = "waifu"
DEFAULT_RESOLUTION = "1920x1080"
